eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_service_db?serverTimezone=UTC
    username: esarygulov
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECTION_TIMEOUT:60000}
        readTimeout: ${FEIGN_CONNECTION_TIMEOUT:60000}
        loggerLevel: basic
  autoconfiguration:
    jackson:
      enabled: true
service:
  stock:
    endpoint: http://localhost:8081
  price:
    endpoint: http://localhost:8082
  product:
    endpoint: http://localhost:8083