eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

service:
  elasticsearch:
    endpoint: http://localhost:9200
  admin:
    endpoint: http://localhost:8080