server:
  port: 8888
spring:
  application:
    name: cloud_config_service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: "/Users/esarygulov/Documents/IdeaProjects/e-commerce_app/cloud_config_service/src/main/resources/config"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true